package com.utils;

public enum Constants {	
	BARCODE_NUMBER("BARCODE"),LOGIN_FAILED("LOGIN_FAILED"),LOGIN_SUCCESSFUL("LOGIN_SUCCESSFUL"),USER_ACTION("USER_ACTION"),
	USER_NAME("USER_NAME"),PASSWORD("PASSWORD"),LOGIN("LOGIN"),CHECK_ALLERGY("CHECK_ALLERGY"),
	ALLERGY_CHECKER_SESSION_OBJECT("ALLERGY_CHECKER_SESSION_OBJECT"),TRUE("TRUE"),FALSE("FALSE"),
	ILLEGAL_STATE("ILLEGAL_STATE"),CHECK_ALLERGY_TEXT("CHECK_ALLERGY_TEXT"),PRODUCT_NAME("PRODUCT_NAME"),
	INVALID_USER_ACTION("OPERATION_FAILED"),
	ERROR_IN_CONNECTING_TO_SERVER("OPERATION_FAILED"),
	SERVER_ERROR("OPERATION_FAILED"),
	CHECK_ALLERGY_OPERATION_FAILED("OPERATION_FAILED");	
	
	String value;
	
	public String getValue(){
		return value;
	}
	
	Constants(String value){
		this.value = value;
	}
}
